#!/usr/bin/env python3
"""Generate a sorted GBK-to-Unicode mapping table using Python's stdlib codec."""

from pathlib import Path


def main() -> None:
    output = Path(__file__).resolve().parents[1] / "src" / "reader" / "gbk_table.c"
    rows: list[tuple[int, int]] = []
    for lead in range(0x81, 0xFF):
        for trail in range(0x40, 0xFF):
            if trail == 0x7F:
                continue
            raw = bytes((lead, trail))
            try:
                text = raw.decode("gbk")
            except UnicodeDecodeError:
                continue
            if len(text) == 1:
                rows.append(((lead << 8) | trail, ord(text)))

    lines = [
        "/* Generated by tools/gen_gbk_table.py; do not edit manually. */",
        '#include "gbk_table.h"',
        "",
        "const gbk_map_entry_t ebook_gbk_table[] = {",
    ]
    lines.extend(f"    {{0x{gbk:04X}, 0x{unicode_:04X}}}," for gbk, unicode_ in rows)
    lines += [
        "};",
        "",
        f"const size_t ebook_gbk_table_count = {len(rows)};",
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {len(rows)} entries: {output}")


if __name__ == "__main__":
    main()
